// swift-tools-version: 6.0
//
// The blm Swift package — one package rooted at the repo, mirroring the single Go
// module. It spans the generated contracts and the apple-silicon on-device provider:
//
//   Contracts        generated Swift Codable for the contracts (gen/swift), read-only
//   Capabilities     the on-device capability core (arbiter + capabilities + router)
//   ProviderService  the wire adapter: maps model.v1 Invoke* onto Capabilities, and
//                    (next) serves it over local HTTP
//
// The provider runs bare-metal on the host — it reaches the Neural Engine and the
// Swift-only Apple frameworks, which a Linux container cannot — and is discovered by
// delightd's poll, reached over the mesh.
import PackageDescription

let package = Package(
    name: "blm",
    platforms: [
        .macOS("26.0"),
    ],
    products: [
        .library(name: "Capabilities", targets: ["Capabilities"]),
        .library(name: "ProviderService", targets: ["ProviderService"]),
    ],
    targets: [
        // Generated Codable structs + enums for the contracts the provider speaks
        // (model.v1, sidecar.v1). Generated by protoc-gen-swift-codable, held by the
        // gen-drift gate; read-only to hand-written code.
        .target(
            name: "Contracts",
            path: "gen/swift"
        ),
        // The capability core: the bounded single-arbiter — one front door to the one
        // Neural Engine per host, so contended work is serialized and overflow is shed as
        // BUSY — plus the transcription/synthesis capabilities and the router. Kept
        // contract-free on purpose; the wire types are mapped onto it in ProviderService.
        .target(
            name: "Capabilities",
            path: "apple-silicon/Sources/Capabilities"
        ),
        // The wire adapter: maps model.v1 InvokeRequest/Response onto the Capabilities
        // router. The Network.framework HTTP transport is added here next.
        .target(
            name: "ProviderService",
            dependencies: ["Capabilities", "Contracts"],
            path: "apple-silicon/Sources/ProviderService"
        ),
        // The daemon: assembles the real capabilities behind one arbiter and serves them
        // over loopback HTTP. Thin -- it wires Capabilities + ProviderService together.
        .executableTarget(
            name: "provider",
            dependencies: ["Capabilities", "ProviderService"],
            path: "apple-silicon/Sources/provider"
        ),
        .testTarget(
            name: "CapabilitiesTests",
            dependencies: ["Capabilities"],
            path: "apple-silicon/Tests/CapabilitiesTests"
        ),
        .testTarget(
            name: "ProviderServiceTests",
            dependencies: ["ProviderService", "Capabilities", "Contracts"],
            path: "apple-silicon/Tests/ProviderServiceTests"
        ),
    ]
)
