// protoc-gen-fsm generates the bento lifecycle harness from the contract's state
// enum, so a service binds behavior by name and never hand-writes a state machine.
//
// It targets the bento lifecycle: the BentoState enum over the Bento message. (One
// state machine for v0.5; generalizing to arbitrary state machines is future work.)
// It emits, per active state value, a handler the service
// must supply. ACTIVE states are value numbers 1..19; 0 is the UNSPECIFIED sentinel
// and >= 20 are RESERVED (declared in the contract to hold the namespace, not yet
// wired) -- the harness skips both. This number convention keeps the contract free
// of per-value annotations.
//
// Language is selected by the `lang` parameter (go|python), one buf.gen.yaml plugin
// entry per language. Go uses qmuntal/stateless; Python uses transitions.
package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	statelessPkg = protogen.GoImportPath("github.com/qmuntal/stateless")
	contextPkg   = protogen.GoImportPath("context")
	fmtPkg       = protogen.GoImportPath("fmt")
)

func main() {
	// lang selects the target; protoc-gen-fsm errors on any other parameter. protogen
	// handles `paths`/`module`/`M` itself before this runs, so they still work.
	lang := "go"
	opts := protogen.Options{
		ParamFunc: func(name, value string) error {
			if name == "lang" {
				lang = value
				return nil
			}
			return fmt.Errorf("protoc-gen-fsm: unknown parameter %q", name)
		},
	}
	opts.Run(func(gen *protogen.Plugin) error {
		// the contract uses proto3 optional/standard features only; declare full support.
		gen.SupportedFeatures = uint64(1) // FEATURE_PROTO3_OPTIONAL
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, e := range f.Enums {
				// v0.5 has one state machine: the bento lifecycle (BentoState over the
				// Bento message). genGo references *Bento, so this is scoped to that
				// enum; generalizing to arbitrary state machines is future work.
				if e.Desc.Name() != "BentoState" {
					continue
				}
				switch lang {
				case "go":
					genGo(gen, f, e)
				case "python":
					genPython(gen, f, e)
				default:
					return fmt.Errorf("protoc-gen-fsm: unknown lang %q (want go|python)", lang)
				}
			}
		}
		return nil
	})
}

// state is one active enum value the harness binds a handler to.
type state struct {
	constIdent protogen.GoIdent // e.g. BentoState_BENTO_STATE_NOTICED
	method     string           // e.g. OnNoticed
	short      string           // e.g. NOTICED
}

// activeStates returns the value enum values in [1,19], in declared order. The 0
// sentinel and the reserved (>= 20) values are skipped.
func activeStates(e *protogen.Enum) []state {
	prefix := screamingSnake(string(e.Desc.Name())) + "_"
	var out []state
	for _, v := range e.Values {
		n := int32(v.Desc.Number())
		if n <= 0 || n >= 20 {
			continue
		}
		short := strings.TrimPrefix(string(v.Desc.Name()), prefix)
		out = append(out, state{
			constIdent: v.GoIdent,
			method:     "On" + camel(short),
			short:      short,
		})
	}
	return out
}

// zeroIdent returns the enum's UNSPECIFIED (number 0) value ident -- the terminal
// sentinel a handler returns to halt.
func zeroIdent(e *protogen.Enum) protogen.GoIdent {
	for _, v := range e.Values {
		if v.Desc.Number() == 0 {
			return v.GoIdent
		}
	}
	return e.Values[0].GoIdent
}

func genGo(gen *protogen.Plugin, f *protogen.File, e *protogen.Enum) {
	states := activeStates(e)
	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+"_fsm.pb.go", f.GoImportPath)
	enum := e.GoIdent.GoName // BentoState
	zero := g.QualifiedGoIdent(zeroIdent(e))
	ctx := g.QualifiedGoIdent(contextPkg.Ident("Context"))
	errorf := g.QualifiedGoIdent(fmtPkg.Ident("Errorf"))
	sm := g.QualifiedGoIdent(statelessPkg.Ident("StateMachine"))
	newSM := g.QualifiedGoIdent(statelessPkg.Ident("NewStateMachine"))

	g.P("// Code generated by protoc-gen-fsm. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	// Handlers interface -- one method per active state, bound by name.
	g.P("// Handlers is the behavior a service binds to the ", enum, " lifecycle. There is one")
	g.P("// method per active state; the harness calls the method for the state a Bento is in,")
	g.P("// takes the ", enum, " it returns as the next state, and emits a lifecycle event for it.")
	g.P("// Returning ", zero, " halts (the state is terminal). The compiler enforces that every")
	g.P("// active state has a handler -- no event, no call; you cannot forget one.")
	g.P("type Handlers interface {")
	for _, s := range states {
		g.P("\t", s.method, "(ctx ", ctx, ", b *Bento) (", enum, ", error)")
	}
	g.P("}")
	g.P()

	// Emitter interface.
	g.P("// Emitter publishes the lifecycle event the harness produces on each transition.")
	g.P("// A nil Emitter is allowed (the harness skips emission) so a Bento can be driven")
	g.P("// locally without the bus.")
	g.P("type Emitter interface {")
	g.P("\tEmitLifecycle(ctx ", ctx, ", b *Bento, st ", enum, ") error")
	g.P("}")
	g.P()

	// dispatch.
	g.P("// dispatch routes a state to its bound handler. Generated; never hand-written.")
	g.P("func dispatch(ctx ", ctx, ", h Handlers, b *Bento, st ", enum, ") (", enum, ", error) {")
	g.P("\tswitch st {")
	for _, s := range states {
		g.P("\tcase ", g.QualifiedGoIdent(s.constIdent), ":")
		g.P("\t\treturn h.", s.method, "(ctx, b)")
	}
	g.P("\tdefault:")
	g.P("\t\treturn ", zero, ", ", errorf, "(\"", f.Desc.Package(), " fsm: no handler for state %v\", st)")
	g.P("\t}")
	g.P("}")
	g.P()

	// activeStateSet.
	g.P("// activeStateSet is the legal state SET the machine enforces. There is no declared")
	g.P("// adjacency (no \"legal successors\"): every active state may transition to every")
	g.P("// active state, and entering an undeclared (e.g. reserved) state is rejected.")
	g.P("func activeStateSet() []", enum, " {")
	g.P("\treturn []", enum, "{")
	for _, s := range states {
		g.P("\t\t", g.QualifiedGoIdent(s.constIdent), ",")
	}
	g.P("\t}")
	g.P("}")
	g.P()

	// newMachine.
	g.P("func newMachine(initial ", enum, ") *", sm, " {")
	g.P("\tm := ", newSM, "(initial)")
	g.P("\tfor _, s := range activeStateSet() {")
	g.P("\t\tc := m.Configure(s)")
	g.P("\t\tfor _, d := range activeStateSet() {")
	g.P("\t\t\tif d == s {")
	g.P("\t\t\t\tc.PermitReentry(d)")
	g.P("\t\t\t} else {")
	g.P("\t\t\t\tc.Permit(d, d)")
	g.P("\t\t\t}")
	g.P("\t\t}")
	g.P("\t}")
	g.P("\treturn m")
	g.P("}")
	g.P()

	// Step -- one transition, then return. The bus is the loop, not an in-process for{}.
	g.P("// Step handles ONE transition and then returns: it dispatches the Bento's current")
	g.P("// state to its handler, validates the single state the handler returns (the machine")
	g.P("// rejects an undeclared state), applies it, and emits the lifecycle event for it.")
	g.P("// It does one job and is done -- the emitted event is what drives the next step, and")
	g.P("// any instance can pick that up. There is no in-process loop holding state across")
	g.P("// steps: the in-flight state lives on the bus (the last lifecycle event) and on the")
	g.P("// Bento, never in memory, so a process may die between steps and another resumes.")
	g.P("// A handler returning ", zero, " is terminal (nothing to emit). Re-handling the same")
	g.P("// event must be idempotent -- the bus may redeliver, and recovery replays.")
	g.P("func Step(ctx ", ctx, ", h Handlers, e Emitter, b *Bento) error {")
	g.P("\tcur := b.GetState()")
	g.P("\tnext, err := dispatch(ctx, h, b, cur)")
	g.P("\tif err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
	g.P("\tif next == ", zero, " {")
	g.P("\t\treturn nil")
	g.P("\t}")
	g.P("\t// build a fresh machine seeded at the current state purely to VALIDATE this one")
	g.P("\t// transition (containment); it is not retained across steps.")
	g.P("\tif err := newMachine(cur).Fire(next); err != nil {")
	g.P("\t\treturn ", errorf, "(\"", f.Desc.Package(), " fsm: illegal transition %v -> %v: %w\", cur, next, err)")
	g.P("\t}")
	g.P("\tb.State = next")
	g.P("\tif e != nil {")
	g.P("\t\treturn e.EmitLifecycle(ctx, b, next)")
	g.P("\t}")
	g.P("\treturn nil")
	g.P("}")
}

// genPython emits the Python harness -- parity with the Go one, over transitions.
func genPython(gen *protogen.Plugin, f *protogen.File, e *protogen.Enum) {
	prefix := screamingSnake(string(e.Desc.Name())) + "_"
	pkg := string(f.Desc.Package())                                          // bento.v1
	module := strings.TrimSuffix(pathBase(f.Desc.Path()), ".proto") + "_pb2" // bento_pb2

	type pystate struct{ value, short, method string }
	var states []pystate
	var zero string
	for _, v := range e.Values {
		n := int32(v.Desc.Number())
		name := string(v.Desc.Name())
		if n == 0 {
			zero = name
			continue
		}
		if n >= 20 {
			continue
		}
		short := strings.ToLower(strings.TrimPrefix(name, prefix))
		states = append(states, pystate{value: name, short: short, method: "on_" + short})
	}

	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+"_fsm.py", f.GoImportPath)
	g.P("# Code generated by protoc-gen-fsm. DO NOT EDIT.")
	g.P("# source: ", f.Desc.Path())
	g.P()
	g.P("from transitions import Machine")
	g.P()
	g.P("from ", pkg, " import ", module)
	g.P()
	g.P()
	// short name -> proto value, active states only (1..19; 0 and >= 20 absent).
	g.P("_STATE_BY_NAME = {")
	for _, s := range states {
		g.P("    \"", s.short, "\": ", module, ".", s.value, ",")
	}
	g.P("}")
	g.P("_NAME_BY_STATE = {v: k for k, v in _STATE_BY_NAME.items()}")
	g.P()
	// state value -> handler method name. dispatch goes through getattr on the instance,
	// so a subclass override is used (and a missing method raises) -- the Python parallel
	// to Go's compiler-enforced Handlers interface.
	g.P("_HANDLER_BY_STATE = {")
	for _, s := range states {
		g.P("    ", module, ".", s.value, ": \"", s.method, "\",")
	}
	g.P("}")
	g.P()
	g.P()
	g.P("class Handlers:")
	g.P("    # the behavior a service binds to the ", e.GoIdent.GoName, " lifecycle: one method per")
	g.P("    # active state. step() calls the method for the state a bento is in, takes the")
	g.P("    # state it returns as the next state, and emits a lifecycle event for it.")
	g.P("    # Returning ", module, ".", zero, " halts (terminal). Subclass and implement all of")
	g.P("    # them; a missing method raises at dispatch.")
	for _, s := range states {
		g.P("    def ", s.method, "(self, b: ", module, ".Bento) -> int:")
		g.P("        raise NotImplementedError")
	}
	g.P()
	g.P()
	g.P("def _new_machine(current):")
	g.P("    # a fresh per-step machine over the legal state SET (no declared adjacency),")
	g.P("    # used only to apply and validate this one transition (containment) -- not")
	g.P("    # retained across steps. transitions' auto to_<state>() exists only for declared")
	g.P("    # states, so a move to an undeclared one has no method.")
	g.P("    return Machine(states=list(_STATE_BY_NAME), initial=_NAME_BY_STATE[current], auto_transitions=True)")
	g.P()
	g.P()
	g.P("def step(handlers, emitter, b):")
	g.P("    # one transition, then return -- the bus is the loop, not an in-process loop, so")
	g.P("    # a process may die between steps and another instance resumes from the bus.")
	g.P("    # Mirrors the Go harness's Step. emitter may be None (driven locally without the")
	g.P("    # bus); if set it is called emitter(b, next_state). Re-handling must be idempotent.")
	g.P("    cur = b.state")
	g.P("    method = _HANDLER_BY_STATE.get(cur)")
	g.P("    if method is None:")
	g.P("        raise ValueError(f\"", pkg, " fsm: no handler for state {cur}\")")
	g.P("    nxt = getattr(handlers, method)(b)")
	g.P("    if nxt == ", module, ".", zero, ":")
	g.P("        return")
	g.P("    name = _NAME_BY_STATE.get(nxt)")
	g.P("    if name is None:")
	g.P("        raise ValueError(f\"", pkg, " fsm: illegal transition {cur} -> {nxt} (undeclared state)\")")
	g.P("    getattr(_new_machine(cur), \"to_\" + name)()")
	g.P("    b.state = nxt")
	g.P("    if emitter is not None:")
	g.P("        emitter(b, nxt)")
}

// pathBase returns the last path element (the proto filename).
func pathBase(p string) string {
	if i := strings.LastIndex(p, "/"); i >= 0 {
		return p[i+1:]
	}
	return p
}

// screamingSnake turns a CamelCase identifier into SCREAMING_SNAKE (BentoState ->
// BENTO_STATE), so the value-name prefix can be stripped to the short state name.
func screamingSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return strings.ToUpper(b.String())
}

// camel turns a SCREAMING_SNAKE short state name into CamelCase (NOT_STARTED ->
// NotStarted) for the handler method name.
func camel(s string) string {
	var b strings.Builder
	for _, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(strings.ToLower(part[1:]))
	}
	return b.String()
}
